language: "en-US"
early_access: true
reviews:
  request_changes_workflow: false
  high_level_summary: true
  poem: true
  review_status: true
  collapse_walkthrough: true
  path_filters:
    - "!**/.xml"
  path_instructions:
    - path: "src/**/*.js"
      instructions: |
        "Review JavaScript Code."
    - path: "src/**/*.jsx"
      instructions: |
        "Review ReactJs Code."
    - path: "src/**/*.ts"
      instructions: |
        "Review TypeScript Code."
    - path: "src/**/*.tsx"
      instructions: |
        "Review ReactJs + TypeScript Code."
  auto_review:
    enabled: true
    ignore_title_keywords:
      - "WIP"
    drafts: true
    base_branches:
      - "develop"
      - "feature/*"
chat:
  auto_reply: true